name: Plagiarism Note Check
on:
  push:

jobs:
  plag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: cat README.md | tr -s '\n\r' '  ' | grep -zq "I certify that I have listed all sources used to complete this exercise, including the use of any Large Language Models. All of the work is my own, except where stated otherwise. I am aware that plagiarism carries severe penalties and that if plagiarism is suspected, charges may be filed against me without prior notice." 
